services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: dumbs
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dumbs
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
